/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trashCode;

import gmailApi.Init;
import gmailApi.MessageObject;
import java.util.List;
import java.awt.Panel;
import java.io.File;
import java.util.ArrayList;
import javafx.application.Application;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import customException.FailToLoadInitInboxException;
import gmailApi.GlobalVariable;
import gmailApi.MessageProcess;
import gmailApi.SendMailProcess;
import gmailApi.XuLyFile;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.io.IOException;
import java.util.Date;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author NTA
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    GridBagLayout layout = new GridBagLayout();

    public index() {
	setLocation(450, 200);
	initComponents();
	//setting dynamic panel for 2 option(Read/write)Panel
	dynamicOption_Pn.setLayout(layout);
	GridBagConstraints c = new GridBagConstraints();
	c.gridx = 0;
	c.gridy = 0;
	this.optionReadMail_Pn.setSize(600, 70);
	dynamicOption_Pn.add(this.optionReadMail_Pn);
	c.gridx = 0;
	c.gridy = 0;
	this.optionWriteMail_Pn.setSize(600, 70);
	dynamicOption_Pn.add(this.optionWriteMail_Pn);
	this.optionReadMail_Pn.setVisible(false);
	this.optionWriteMail_Pn.setVisible(false);

	loadStartUpMailBox();
	list_mailbox_panel.setVisible(true);
	mail_panel.setVisible(false);

    }
    public List<MessageObject> messageInbox;
//    ArrayList<MessageObject> demo = new ArrayList<>();    
//    MessageObject demo1 = new MessageObject("Tuan@gmail.com", "Deadline", "2 tuan truoc thi !", "20/03/2020", "tuan");                                       //đổ dữ liệu để test thôi
//    MessageObject demo2 = new MessageObject("Thom@gmail.com", "Hello ", "How are you to day", "10/04/2020", "thom");                                         //
//    MessageObject demo3 = new MessageObject("An@gmail.com", "Demo", " aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaâ", "15/04/2020", "An");   //
//    MessageObject demo4 = new MessageObject("Tuan1@gmail.com", "Deadline1", "2 tuan truoc thi !", "20/03/2020", "tuan");                                       //đổ dữ liệu để test thôi
//    MessageObject demo5 = new MessageObject("Thom1@gmail.com", "Hello1 ", "How are you to day", "10/04/2020", "thom");                                         //
//    MessageObject demo6 = new MessageObject("An1@gmail.com", "Demo1", " aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaâ", "15/04/2020", "An");

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        read_mail_file_cbx = new javax.swing.JTextField();
        menu_new_panel = new javax.swing.JPanel();
        menu_trash_panel = new javax.swing.JPanel();
        menu_mailbox_panel1 = new javax.swing.JPanel();
        menu_mailbox_panel = new javax.swing.JPanel();
        optionReadMail_Pn = new javax.swing.JPanel();
        read_mail_reply = new javax.swing.JLabel();
        read_mail_trash = new javax.swing.JLabel();
        lb_1 = new javax.swing.JLabel();
        read_mail_download = new javax.swing.JLabel();
        read_mail_file_Jcb = new javax.swing.JComboBox<>();
        background_all = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        mail_panel = new javax.swing.JPanel();
        lb_nothing2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mail_content = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        mail_to = new javax.swing.JTextField();
        mail_cc = new javax.swing.JTextField();
        mail_bcc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        mail_subject = new javax.swing.JTextField();
        mail_from = new javax.swing.JTextField();
        read_mail_date = new javax.swing.JTextField();
        date_Lb = new javax.swing.JLabel();
        menu_panel = new javax.swing.JPanel();
        lb_hide_menu = new javax.swing.JLabel();
        newMail_Lb = new javax.swing.JLabel();
        trash_Lb = new javax.swing.JLabel();
        inbox_Lb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        list_mailbox_panel = new javax.swing.JPanel();
        list_mailbox_search = new javax.swing.JTextField();
        mailbox_search = new javax.swing.JLabel();
        mailbox_reset = new javax.swing.JLabel();
        jScroll_mailbox = new javax.swing.JScrollPane();
        list_mailbox = new javax.swing.JList<>();
        lb_name = new javax.swing.JLabel();
        prevLoadMail_Bt = new javax.swing.JButton();
        nextLoadMail_Bt = new javax.swing.JButton();
        lb_name_mail = new javax.swing.JLabel();
        background_img = new javax.swing.JLabel();
        dynamicOption_Pn = new javax.swing.JPanel();
        optionWriteMail_Pn = new javax.swing.JPanel();
        writeMailSent_Lb = new javax.swing.JLabel();
        writeMailCancel_Lb = new javax.swing.JLabel();
        fileChoose_Lb = new javax.swing.JLabel();
        writeMailSelectFile_Bt = new javax.swing.JButton();
        writeMailfileInput_Jcb = new javax.swing.JComboBox<>();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        read_mail_file_cbx.setEditable(false);

        menu_new_panel.setToolTipText("New");
        menu_new_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_new_panel.setOpaque(false);
        menu_new_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_new_panelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu_new_panelLayout = new javax.swing.GroupLayout(menu_new_panel);
        menu_new_panel.setLayout(menu_new_panelLayout);
        menu_new_panelLayout.setHorizontalGroup(
            menu_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        menu_new_panelLayout.setVerticalGroup(
            menu_new_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        menu_trash_panel.setToolTipText("Trash");
        menu_trash_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_trash_panel.setOpaque(false);
        menu_trash_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_trash_panelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu_trash_panelLayout = new javax.swing.GroupLayout(menu_trash_panel);
        menu_trash_panel.setLayout(menu_trash_panelLayout);
        menu_trash_panelLayout.setHorizontalGroup(
            menu_trash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        menu_trash_panelLayout.setVerticalGroup(
            menu_trash_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        menu_mailbox_panel1.setToolTipText("Mail Box");
        menu_mailbox_panel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_mailbox_panel1.setOpaque(false);
        menu_mailbox_panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_mailbox_panel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu_mailbox_panel1Layout = new javax.swing.GroupLayout(menu_mailbox_panel1);
        menu_mailbox_panel1.setLayout(menu_mailbox_panel1Layout);
        menu_mailbox_panel1Layout.setHorizontalGroup(
            menu_mailbox_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        menu_mailbox_panel1Layout.setVerticalGroup(
            menu_mailbox_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        menu_mailbox_panel.setToolTipText("Mail Box");
        menu_mailbox_panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu_mailbox_panel.setOpaque(false);
        menu_mailbox_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_mailbox_panelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu_mailbox_panelLayout = new javax.swing.GroupLayout(menu_mailbox_panel);
        menu_mailbox_panel.setLayout(menu_mailbox_panelLayout);
        menu_mailbox_panelLayout.setHorizontalGroup(
            menu_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        menu_mailbox_panelLayout.setVerticalGroup(
            menu_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        optionReadMail_Pn.setBackground(new java.awt.Color(39, 129, 191));
        optionReadMail_Pn.setPreferredSize(new java.awt.Dimension(662, 67));

        read_mail_reply.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_reply.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_reply.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_reply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reply-arrow-35.png"))); // NOI18N
        read_mail_reply.setText("Reply");
        read_mail_reply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_reply.setOpaque(true);
        read_mail_reply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_replyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_replyMouseExited(evt);
            }
        });

        read_mail_trash.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_trash.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_trash.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_trash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancel-35.png"))); // NOI18N
        read_mail_trash.setText("Trash");
        read_mail_trash.setToolTipText("Move current mail to trash");
        read_mail_trash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_trash.setOpaque(true);
        read_mail_trash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_trashMouseExited(evt);
            }
        });

        lb_1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lb_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-file-30.png"))); // NOI18N
        lb_1.setText("File ");

        read_mail_download.setBackground(new java.awt.Color(39, 129, 191));
        read_mail_download.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        read_mail_download.setForeground(new java.awt.Color(255, 255, 255));
        read_mail_download.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-download-35.png"))); // NOI18N
        read_mail_download.setText("Save mail");
        read_mail_download.setToolTipText("Download current mail");
        read_mail_download.setAlignmentX(0.2F);
        read_mail_download.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        read_mail_download.setOpaque(true);
        read_mail_download.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                read_mail_downloadMouseExited(evt);
            }
        });

        read_mail_file_Jcb.setToolTipText("Click on file to download");
        read_mail_file_Jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_file_JcbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionReadMail_PnLayout = new javax.swing.GroupLayout(optionReadMail_Pn);
        optionReadMail_Pn.setLayout(optionReadMail_PnLayout);
        optionReadMail_PnLayout.setHorizontalGroup(
            optionReadMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                .addComponent(lb_1)
                .addGap(5, 5, 5)
                .addComponent(read_mail_file_Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(read_mail_download)
                .addGap(24, 24, 24)
                .addComponent(read_mail_trash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(read_mail_reply, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionReadMail_PnLayout.setVerticalGroup(
            optionReadMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                .addGroup(optionReadMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lb_1))
                    .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(read_mail_file_Jcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(read_mail_download))
                    .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(read_mail_trash))
                    .addGroup(optionReadMail_PnLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(read_mail_reply)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 625));

        background_all.setFocusable(false);
        background_all.setMinimumSize(new java.awt.Dimension(1000, 625));
        background_all.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(172, 93, 93));
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        logo.setText("GMAIL");
        background_all.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        mail_panel.setOpaque(false);

        lb_nothing2.setText("From :");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setOpaque(false);

        mail_content.setEditable(false);
        mail_content.setColumns(20);
        mail_content.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mail_content.setLineWrap(true);
        mail_content.setRows(5);
        jScrollPane4.setViewportView(mail_content);

        jLabel10.setText("To :");

        jLabel18.setText("Cc :");

        jLabel19.setText("Bcc :");

        mail_to.setEditable(false);
        mail_to.setOpaque(false);
        mail_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_toActionPerformed(evt);
            }
        });

        mail_cc.setEditable(false);
        mail_cc.setOpaque(false);

        mail_bcc.setEditable(false);
        mail_bcc.setOpaque(false);

        jLabel20.setText("Subject :");

        mail_subject.setEditable(false);
        mail_subject.setOpaque(false);

        mail_from.setEditable(false);
        mail_from.setOpaque(false);
        mail_from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mail_fromActionPerformed(evt);
            }
        });

        read_mail_date.setEditable(false);
        read_mail_date.setOpaque(false);
        read_mail_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read_mail_dateActionPerformed(evt);
            }
        });

        date_Lb.setText("Date :");

        javax.swing.GroupLayout mail_panelLayout = new javax.swing.GroupLayout(mail_panel);
        mail_panel.setLayout(mail_panelLayout);
        mail_panelLayout.setHorizontalGroup(
            mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mail_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mail_panelLayout.createSequentialGroup()
                        .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel10)
                            .addComponent(lb_nothing2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mail_bcc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail_cc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail_to, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mail_panelLayout.createSequentialGroup()
                                .addComponent(mail_from)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(date_Lb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(read_mail_date, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(mail_subject))
                        .addGap(47, 47, 47))
                    .addGroup(mail_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mail_panelLayout.setVerticalGroup(
            mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mail_panelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date_Lb)
                        .addComponent(read_mail_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_nothing2)
                        .addComponent(mail_from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail_to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(mail_cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(mail_bcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mail_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background_all.add(mail_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 80, 680, 460));

        menu_panel.setBackground(new java.awt.Color(54, 70, 78));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_hide_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-menu-30.png"))); // NOI18N
        lb_hide_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_hide_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_hide_menuMouseExited(evt);
            }
        });
        menu_panel.add(lb_hide_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 40));

        newMail_Lb.setBackground(new java.awt.Color(102, 204, 255));
        newMail_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        newMail_Lb.setForeground(new java.awt.Color(255, 255, 255));
        newMail_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-add-file-40.png"))); // NOI18N
        newMail_Lb.setToolTipText("New mail");
        newMail_Lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newMail_LbMouseClicked(evt);
            }
        });
        menu_panel.add(newMail_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        trash_Lb.setBackground(new java.awt.Color(102, 204, 255));
        trash_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        trash_Lb.setForeground(new java.awt.Color(255, 255, 255));
        trash_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trash-45.png"))); // NOI18N
        menu_panel.add(trash_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        inbox_Lb.setBackground(new java.awt.Color(102, 204, 255));
        inbox_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        inbox_Lb.setForeground(new java.awt.Color(255, 255, 255));
        inbox_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-chat-message-sent-45.png"))); // NOI18N
        inbox_Lb.setToolTipText("Mail INBOX");
        inbox_Lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inbox_LbMouseClicked(evt);
            }
        });
        menu_panel.add(inbox_Lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 204, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-upload-mail-40.png"))); // NOI18N
        menu_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        background_all.add(menu_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 65, 550));

        list_mailbox_panel.setBackground(new java.awt.Color(255, 255, 255));

        list_mailbox_search.setOpaque(false);

        mailbox_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-20.png"))); // NOI18N

        mailbox_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reset-28.png"))); // NOI18N

        list_mailbox.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        list_mailbox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        list_mailbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_mailboxMouseClicked(evt);
            }
        });
        list_mailbox.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_mailboxValueChanged(evt);
            }
        });
        jScroll_mailbox.setViewportView(list_mailbox);

        lb_name.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lb_name.setText("Mail Box");

        prevLoadMail_Bt.setText("<");

        nextLoadMail_Bt.setBackground(new java.awt.Color(39, 129, 191));
        nextLoadMail_Bt.setText(">");

        javax.swing.GroupLayout list_mailbox_panelLayout = new javax.swing.GroupLayout(list_mailbox_panel);
        list_mailbox_panel.setLayout(list_mailbox_panelLayout);
        list_mailbox_panelLayout.setHorizontalGroup(
            list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                        .addComponent(list_mailbox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mailbox_search, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mailbox_reset)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_mailbox_panelLayout.createSequentialGroup()
                        .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScroll_mailbox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                                .addComponent(prevLoadMail_Bt)
                                .addGap(34, 34, 34)
                                .addComponent(lb_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextLoadMail_Bt)))
                        .addGap(24, 24, 24))))
        );
        list_mailbox_panelLayout.setVerticalGroup(
            list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_mailbox_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(list_mailbox_search, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(mailbox_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mailbox_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScroll_mailbox, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(list_mailbox_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevLoadMail_Bt)
                    .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextLoadMail_Bt))
                .addContainerGap())
        );

        background_all.add(list_mailbox_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 75, 250, 550));

        lb_name_mail.setForeground(new java.awt.Color(0, 51, 51));
        lb_name_mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-change-user-45.png"))); // NOI18N
        background_all.add(lb_name_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, 210, 30));

        background_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FMainMenu.png"))); // NOI18N
        background_img.setText("jLabel1");
        background_all.add(background_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 1000, 630));

        optionWriteMail_Pn.setBackground(new java.awt.Color(39, 129, 191));
        optionWriteMail_Pn.setPreferredSize(new java.awt.Dimension(662, 67));
        optionWriteMail_Pn.setRequestFocusEnabled(false);

        writeMailSent_Lb.setBackground(new java.awt.Color(39, 129, 191));
        writeMailSent_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        writeMailSent_Lb.setForeground(new java.awt.Color(255, 255, 255));
        writeMailSent_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-sent-35.png"))); // NOI18N
        writeMailSent_Lb.setText("Sent");
        writeMailSent_Lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        writeMailSent_Lb.setOpaque(true);
        writeMailSent_Lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writeMailSent_LbMouseClicked(evt);
            }
        });

        writeMailCancel_Lb.setBackground(new java.awt.Color(39, 129, 191));
        writeMailCancel_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        writeMailCancel_Lb.setForeground(new java.awt.Color(255, 255, 255));
        writeMailCancel_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cancel-35.png"))); // NOI18N
        writeMailCancel_Lb.setText("Cancel");
        writeMailCancel_Lb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        writeMailCancel_Lb.setOpaque(true);
        writeMailCancel_Lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                writeMailCancel_LbMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                writeMailCancel_LbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                writeMailCancel_LbMouseExited(evt);
            }
        });

        fileChoose_Lb.setBackground(new java.awt.Color(39, 129, 191));
        fileChoose_Lb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        fileChoose_Lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-file-30.png"))); // NOI18N
        fileChoose_Lb.setText("File ");

        writeMailSelectFile_Bt.setBackground(new java.awt.Color(39, 129, 191));
        writeMailSelectFile_Bt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        writeMailSelectFile_Bt.setText("Select file");
        writeMailSelectFile_Bt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        writeMailSelectFile_Bt.setOpaque(false);
        writeMailSelectFile_Bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeMailSelectFile_BtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionWriteMail_PnLayout = new javax.swing.GroupLayout(optionWriteMail_Pn);
        optionWriteMail_Pn.setLayout(optionWriteMail_PnLayout);
        optionWriteMail_PnLayout.setHorizontalGroup(
            optionWriteMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionWriteMail_PnLayout.createSequentialGroup()
                .addComponent(fileChoose_Lb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(writeMailfileInput_Jcb, 0, 227, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(writeMailSelectFile_Bt)
                .addGap(18, 18, 18)
                .addComponent(writeMailCancel_Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(writeMailSent_Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        optionWriteMail_PnLayout.setVerticalGroup(
            optionWriteMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionWriteMail_PnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionWriteMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(optionWriteMail_PnLayout.createSequentialGroup()
                        .addComponent(writeMailfileInput_Jcb)
                        .addGap(9, 9, 9))
                    .addGroup(optionWriteMail_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(writeMailSelectFile_Bt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(writeMailCancel_Lb)
                        .addComponent(writeMailSent_Lb)
                        .addComponent(fileChoose_Lb)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dynamicOption_PnLayout = new javax.swing.GroupLayout(dynamicOption_Pn);
        dynamicOption_Pn.setLayout(dynamicOption_PnLayout);
        dynamicOption_PnLayout.setHorizontalGroup(
            dynamicOption_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(dynamicOption_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicOption_PnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(optionWriteMail_Pn, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        dynamicOption_PnLayout.setVerticalGroup(
            dynamicOption_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(dynamicOption_PnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dynamicOption_PnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(optionWriteMail_Pn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        background_all.add(dynamicOption_Pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 670, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_trash_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_trash_panelMouseExited

    private void menu_trash_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_trash_panelMouseEntered

    private void menu_new_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_new_panelMouseExited

    private void menu_new_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_new_panelMouseEntered

    private void lb_hide_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseExited

    }//GEN-LAST:event_lb_hide_menuMouseExited

    private void lb_hide_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseEntered

    }//GEN-LAST:event_lb_hide_menuMouseEntered

    private void lb_hide_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hide_menuMouseClicked
	// TODO add your handling code here:
//        panelcoler(menu_mailbox_panel);
//        panelreset(menu_new_panel);
//        panelreset(menu_trash_panel);
//        if (x == 65) {
//            menu_panel.setSize(x, 552);
//            Thread th;
//            th = new Thread() {
//                @Override
//                public void run() {
//                    try {
//                        for (int i = 65; i <= x; i++) {
//                            Thread.sleep(1);
//                            menu_panel.setSize(i, 552);
//                        }
//                    } catch (InterruptedException e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//            };
//            th.start();
//            list_mailbox_panel.setVisible(false);
//            x = 315;
//        } else if (x == 315) {
//            menu_panel.setSize(315, 552);
//            Thread th;
//            th = new Thread() {
//                @Override
//                public void run() {
//                    try {
//
//                        for (int i = 315; i >= 65; i--) {
//                            Thread.sleep(1);
//                            menu_panel.setSize(i, 552);
//
//                            a++;
//                        }
//                    } catch (InterruptedException e) {
//                        JOptionPane.showMessageDialog(null, e);
//                    }
//                }
//            };
//            th.start();
//            list_mailbox_panel.setVisible(true);
//            x = 65;
//        }
    }//GEN-LAST:event_lb_hide_menuMouseClicked
    String name;
    private void menu_mailbox_panelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panelMouseExited

    private void menu_mailbox_panelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panelMouseEntered

    private void menu_mailbox_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panelMouseClicked
	// TODO add your handling code here:
	name = "mail box";
	panelreset(menu_trash_panel);
	panelcoler(menu_mailbox_panel);
	panelreset(menu_new_panel);
	list_mailbox_panel.setVisible(true);
	mail_panel.setVisible(true);
	loadStartUpMailBox();
    }//GEN-LAST:event_menu_mailbox_panelMouseClicked

    private void list_mailboxValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_mailboxValueChanged
	// TODO add your handling code here:
    }//GEN-LAST:event_list_mailboxValueChanged

    private void list_mailboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_mailboxMouseClicked
	// TODO add your handling code here:
	int chon = list_mailbox.getSelectedIndex();
	if (chon != -1) {
	    mail_panel.setVisible(true);
	    panelreset(menu_trash_panel);
	    panelcoler(menu_mailbox_panel);
	    panelreset(menu_new_panel);
	    MessageObject msgOb = messageInbox.get(chon);
	    MessageProcess.loadMessage(msgOb);
	    mail_from.setText(msgOb.from);
	    mail_to.setText(msgOb.to);
	    mail_cc.setText(msgOb.cc);
	    mail_subject.setText(msgOb.subject);
	    read_mail_date.setText(msgOb.date);
	    mail_content.setText(msgOb.mainText);
	    // load file len
	    DefaultComboBoxModel model = new DefaultComboBoxModel();
	    for (Map.Entry m : msgOb.listFile.entrySet()) {
		model.addElement(m.getKey());
	    }
	    this.read_mail_file_Jcb.setModel(model);
	    // vo hieu hoa bcc vi reader khong the thay bcc
	    mail_bcc.setEnabled(true);
	    mail_panel.setVisible(true);
	}
    }//GEN-LAST:event_list_mailboxMouseClicked

    private void menu_trash_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_trash_panelMouseClicked
	// TODO add your handling code here:
	name = "trash";
	panelcoler(menu_trash_panel);
	panelreset(menu_mailbox_panel);
	panelreset(menu_new_panel);
	showListTrashDemo();
    }//GEN-LAST:event_menu_trash_panelMouseClicked

    private void menu_new_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_new_panelMouseClicked
	// TODO add your handling code here:
	panelreset(menu_trash_panel);
	panelreset(menu_mailbox_panel);
	panelcoler(menu_new_panel);
	mail_panel.setVisible(false);

    }//GEN-LAST:event_menu_new_panelMouseClicked

    private void mail_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_toActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_mail_toActionPerformed

    private void read_mail_replyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_replyMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_reply);
    }//GEN-LAST:event_read_mail_replyMouseEntered

    private void read_mail_replyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_replyMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_reply);
    }//GEN-LAST:event_read_mail_replyMouseExited
    private void cleanReadMailPanel() {
	mail_from.setText("");
	mail_bcc.setText("");
	mail_cc.setText("");
	mail_subject.setText("");
	mail_to.setText("");
	mail_content.setText("");
	read_mail_file_Jcb.removeAllItems();
	read_mail_date.setText("");
    }

    private void deleteTheMailToTrash() {
	int index = list_mailbox.getSelectedIndex();
	DefaultListModel listMail = (DefaultListModel) list_mailbox.getModel();
	listMail.remove(index);
	list_mailbox.setModel(listMail);
	messageInbox.remove(index);
    }
    private void read_mail_trashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseClicked
	// TODO add your handling code here:
	int confirmResponse = JOptionPane.showConfirmDialog(this, "Bạn có chăc muốn đưa mail này vào thùng rác không?");
	if (confirmResponse == JOptionPane.YES_OPTION) {
	    int chon = list_mailbox.getSelectedIndex();
	    MessageObject msgOb = messageInbox.get(chon);
	    try {
		MessageProcess.moveToTrash(msgOb.id);
		cleanReadMailPanel();
		deleteTheMailToTrash();
	    } catch (IOException ex) {
		Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
    }//GEN-LAST:event_read_mail_trashMouseClicked

    private void read_mail_trashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_trash);
    }//GEN-LAST:event_read_mail_trashMouseEntered

    private void read_mail_trashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_trashMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_trash);
    }//GEN-LAST:event_read_mail_trashMouseExited

    private void mail_fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mail_fromActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_mail_fromActionPerformed

    private void read_mail_downloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseClicked
	// TODO add your handling code here:
//	System.out.println("click on download !");
	String pathDir = XuLyFile.showOpenDirDialog();
	int chon = list_mailbox.getSelectedIndex();
	MessageObject msgOb = messageInbox.get(chon);
	MessageProcess.downloadMail(msgOb, pathDir);
    }//GEN-LAST:event_read_mail_downloadMouseClicked

    private void read_mail_downloadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseEntered
	// TODO add your handling code here:
	labelcolor(read_mail_download);
    }//GEN-LAST:event_read_mail_downloadMouseEntered

    private void read_mail_downloadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_read_mail_downloadMouseExited
	// TODO add your handling code here:
	resetlabelcolor(read_mail_download);
    }//GEN-LAST:event_read_mail_downloadMouseExited

    private void read_mail_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_dateActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_read_mail_dateActionPerformed

    private void menu_mailbox_panel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseClicked

    private void menu_mailbox_panel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseEntered

    private void menu_mailbox_panel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_mailbox_panel1MouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_menu_mailbox_panel1MouseExited

    private void read_mail_file_JcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read_mail_file_JcbActionPerformed
	try {
	    // TODO add your handling code here:
	    String pathDir = XuLyFile.showOpenDirDialog();
	    String fileName = (String) this.read_mail_file_Jcb.getSelectedItem();
	    String fileAttId;
	    int chon = list_mailbox.getSelectedIndex();
	    MessageObject msgOb = messageInbox.get(chon);
	    fileAttId = msgOb.listFile.get(fileName);
	    MessageProcess.downloadAttach(msgOb.id, fileAttId, pathDir + fileName);
	} catch (IOException ex) {
	    Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_read_mail_file_JcbActionPerformed

    private void newMail_LbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newMail_LbMouseClicked
	// TODO add your handling code here:
	cleanReadMailPanel();
	this.mail_panel.setVisible(true);

	this.optionReadMail_Pn.setVisible(false);
	this.optionWriteMail_Pn.setVisible(true);

	this.mail_from.setEditable(false);
	this.mail_from.setText(GlobalVariable.userId);
	this.read_mail_date.setEditable(false);
	this.read_mail_date.setText((new Date()).toString());
	this.mail_to.setEditable(true);
	this.mail_cc.setEditable(true);
	this.mail_bcc.setEditable(true);
	this.mail_subject.setEditable(true);
	this.mail_content.setEditable(true);
	this.mail_bcc.setToolTipText("Các mail đặt cách nhau bỏi dấu ';'");
	this.mail_cc.setToolTipText("Các mail đặt cách nhau bỏi dấu ';'");
	this.mail_to.setToolTipText("Các mail đặt cách nhau bỏi dấu ';'");
//	this.optionReadMail_Pn.remove(this.read_mail_trash);
//	this.optionReadMail_Pn.remove(this.read_mail_reply);
//	this.write_mail_sent.setVisible(true);
//	this.write_mail_cancel.setVisible(true);
//	this.optionReadMail_Pn.add(this.write_mail_sent);
//	this.optionReadMail_Pn.add(this.write_mail_cancel);

    }//GEN-LAST:event_newMail_LbMouseClicked

    private void writeMailCancel_LbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeMailCancel_LbMouseClicked
	// TODO add your handling code here:
    }//GEN-LAST:event_writeMailCancel_LbMouseClicked

    private void writeMailCancel_LbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeMailCancel_LbMouseEntered
	// TODO add your handling code here:
    }//GEN-LAST:event_writeMailCancel_LbMouseEntered

    private void writeMailCancel_LbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeMailCancel_LbMouseExited
	// TODO add your handling code here:
    }//GEN-LAST:event_writeMailCancel_LbMouseExited

    private void writeMailSelectFile_BtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeMailSelectFile_BtActionPerformed
	// TODO add your handling code here:
	String filePath = XuLyFile.showOpenFileDialog();
	this.writeMailfileInput_Jcb.addItem(filePath);
    }//GEN-LAST:event_writeMailSelectFile_BtActionPerformed

    private void inbox_LbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inbox_LbMouseClicked
	// TODO add your handling code here:
	cleanReadMailPanel();
	this.optionReadMail_Pn.setVisible(true);
	this.optionWriteMail_Pn.setVisible(false);
    }//GEN-LAST:event_inbox_LbMouseClicked

    private void writeMailSent_LbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_writeMailSent_LbMouseClicked
	// TODO add your handling code here:
	String[] bcc = null;
	String[] cc = null;
	String[] to = null;
	List<String> listFile = null;
	if (this.mail_to.getText().equals("")) {
	    JOptionPane.showMessageDialog(this, "Bạn chưa nhập mail người cần nhận ! Xin vui lòng nhập đầy đủ !");
	} else {
	    if (!this.mail_bcc.getText().isEmpty()) {
		bcc = this.mail_bcc.getText().split(";");
	    }
	    if (!this.mail_cc.getText().isEmpty()) {
		cc = this.mail_cc.getText().split(";");
	    }
	    if (!this.mail_to.getText().isEmpty()) {
		to = this.mail_to.getText().split(";");
	    }
	    String subject = this.mail_subject.getText();
	    String mainText = this.mail_content.getText();
	    int numOfFile = this.writeMailfileInput_Jcb.getItemCount();
	    if (numOfFile != 0) {
		listFile = new ArrayList<>();
		for (int i = 0; i < numOfFile; i++) {
		    listFile.add(this.writeMailfileInput_Jcb.getItemAt(i));
		}
	    }
	    SendMailProcess newMail = new SendMailProcess(to, cc, bcc, subject, mainText, listFile);
	    try {
		newMail.setUpAndSend();
		JOptionPane.showMessageDialog(this, "Bạn đã gửi mail thành công !");
		cleanReadMailPanel();
	    } catch (MessagingException | IOException ex) {
		Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
		JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi trong quá trình gửi mail !");
	    }
	}
    }//GEN-LAST:event_writeMailSent_LbMouseClicked

    /**
     * * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    // nimbus = windows: java ui ux
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new index().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background_all;
    private javax.swing.JLabel background_img;
    private javax.swing.JLabel date_Lb;
    private javax.swing.JPanel dynamicOption_Pn;
    private javax.swing.JLabel fileChoose_Lb;
    private javax.swing.JLabel inbox_Lb;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScroll_mailbox;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_hide_menu;
    private javax.swing.JLabel lb_name;
    public static javax.swing.JLabel lb_name_mail;
    private javax.swing.JLabel lb_nothing2;
    private javax.swing.JList<MessageObject> list_mailbox;
    private javax.swing.JPanel list_mailbox_panel;
    private javax.swing.JTextField list_mailbox_search;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField mail_bcc;
    private javax.swing.JTextField mail_cc;
    private javax.swing.JTextArea mail_content;
    private javax.swing.JTextField mail_from;
    private javax.swing.JPanel mail_panel;
    private javax.swing.JTextField mail_subject;
    public javax.swing.JTextField mail_to;
    private javax.swing.JLabel mailbox_reset;
    private javax.swing.JLabel mailbox_search;
    private javax.swing.JPanel menu_mailbox_panel;
    private javax.swing.JPanel menu_mailbox_panel1;
    private javax.swing.JPanel menu_new_panel;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JPanel menu_trash_panel;
    private javax.swing.JLabel newMail_Lb;
    private javax.swing.JButton nextLoadMail_Bt;
    private javax.swing.JPanel optionReadMail_Pn;
    private javax.swing.JPanel optionWriteMail_Pn;
    private javax.swing.JButton prevLoadMail_Bt;
    private javax.swing.JTextField read_mail_date;
    private javax.swing.JLabel read_mail_download;
    private javax.swing.JComboBox<String> read_mail_file_Jcb;
    private javax.swing.JTextField read_mail_file_cbx;
    private javax.swing.JLabel read_mail_reply;
    private javax.swing.JLabel read_mail_trash;
    private javax.swing.JLabel trash_Lb;
    private javax.swing.JLabel writeMailCancel_Lb;
    private javax.swing.JButton writeMailSelectFile_Bt;
    private javax.swing.JLabel writeMailSent_Lb;
    private javax.swing.JComboBox<String> writeMailfileInput_Jcb;
    // End of variables declaration//GEN-END:variables
    private void labelcolor(JLabel label) {
	label.setBackground(new java.awt.Color(53, 162, 107));
    }

    private void resetlabelcolor(JLabel label) {
	label.setBackground(new java.awt.Color(39, 129, 191));
    }

    private void panelcoler(JPanel panel) {
	panel.setOpaque(true);
	panel.setBackground(new java.awt.Color(39, 129, 191));
    }

    private void panelreset(JPanel panel) {
	panel.setOpaque(false);
	panel.setBackground(new java.awt.Color(54, 70, 78));

    }

    private void loadStartUpMailBox() {
	if (GlobalVariable.internetOn = true) {
	    lb_name.setText("Mail Box");
	    DefaultListModel listMail = new DefaultListModel(); // khởi tạo Listmodel để đổ dữ liệu vào
	    try {
		messageInbox = Init.initInboxList("INBOX");

		list_mailbox.setModel(listMail);                      // đổ dữ liệu từ listmodel đã tạo ở trên vào cái hiển thị
//		list_mailbox.setCellRenderer(new mailListRender());   // set các cell trong list lại .
		for (int i = 0; i < messageInbox.size(); i++) {
		    listMail.add(i, messageInbox.get(i));
		}
	    } catch (FailToLoadInitInboxException ex) {
		Logger.getLogger(index.class.getName()).log(Level.SEVERE, null, ex);
	    }
	} else {

	}
    }

    private void showListTrashDemo() {
//        lb_name.setText("Trash");
//        DefaultListModel listMail2 = new DefaultListModel(); // khởi tạo Listmodel để đổ dữ liệu vào
//        demo.add(3, demo4);
//        demo.add(4, demo5);
//        demo.add(5, demo6);
//        list_mailbox.setModel(listMail2);                      // đổ dữ liệu từ listmodel đã tạo ở trên vào cái hiển thị
//        list_mailbox.setCellRenderer(new mailListRender());   // set các cell trong list lại .
//        listMail2.add(0, demo.get(3));
//        listMail2.add(1, demo.get(4));
//        listMail2.add(2, demo.get(5));
    }
}
