/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trashCode;

import customException.WrongLoginInfoException;
import gmailApi.CheckInternetConnection;
import gmailApi.GlobalVariable;
import gmailApi.Init;
import gmailApi.LoginProcess;
import gmailApi.XuLyFile;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author NTA
 */
public class welcome extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    public welcome() {
	setLocation(550, 300);
	initComponents();
	this.initJCBoxLoadSaveToken();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_wc = new javax.swing.JLabel();
        lb_mail = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        cb_remember = new javax.swing.JCheckBox();
        bt_start = new javax.swing.JButton();
        lb_error = new javax.swing.JLabel();
        jCboxLoadSaveToken = new javax.swing.JComboBox<>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_wc.setFont(new java.awt.Font("Hobo Std", 3, 48)); // NOI18N
        lb_wc.setForeground(new java.awt.Color(51, 51, 51));
        lb_wc.setText("WELCOME");
        getContentPane().add(lb_wc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 280, 60));

        lb_mail.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lb_mail.setForeground(new java.awt.Color(51, 51, 51));
        lb_mail.setText("Your email :");
        getContentPane().add(lb_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 30));

        tf_email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tf_email.setForeground(new java.awt.Color(51, 51, 51));
        tf_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_emailMouseClicked(evt);
            }
        });
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 260, 30));

        cb_remember.setBackground(new java.awt.Color(98, 194, 236));
        cb_remember.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        cb_remember.setForeground(new java.awt.Color(51, 51, 51));
        cb_remember.setText("Remember your email");
        getContentPane().add(cb_remember, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        bt_start.setBackground(new java.awt.Color(51, 51, 51));
        bt_start.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        bt_start.setForeground(new java.awt.Color(98, 194, 236));
        bt_start.setText("START");
        bt_start.setBorderPainted(false);
        bt_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_startActionPerformed(evt);
            }
        });
        getContentPane().add(bt_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 100, 40));

        lb_error.setForeground(new java.awt.Color(255, 51, 51));
        lb_error.setText(" Please enter the correct mail format");
        lb_error.setVisible(false);
        lb_error.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lb_errorComponentHidden(evt);
            }
        });
        getContentPane().add(lb_error, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, 20));

        jCboxLoadSaveToken.setMaximumRowCount(4);
        jCboxLoadSaveToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboxLoadSaveTokenActionPerformed(evt);
            }
        });
        getContentPane().add(jCboxLoadSaveToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mail3.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initJCBoxLoadSaveToken() {
	List<String> listSaveToken = Init.initSaveTokens();
	this.jCboxLoadSaveToken.addItem("");
	for (String token : listSaveToken) {
	    this.jCboxLoadSaveToken.addItem(token);
	}
    }

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void bt_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_startActionPerformed
	// TODO add your handling code here:
	GlobalVariable.userId = tf_email.getText();
	GlobalVariable.save = this.cb_remember.isSelected() ? 1 : 0; // kiểm tra xem cb_remember có được tick vào hay không
	if (this.jCboxLoadSaveToken.getSelectedItem().toString().equals(GlobalVariable.userId)) {
	    GlobalVariable.save = 1;							 //nếu có trả về 1, không trả về 0
	}
	if (checkmail() == 1) {
	    lb_error.setVisible(true);
	} else {
	    try {
		CheckInternetConnection.checkInternetConnect();
		GlobalVariable.internetOn = true;
	    } catch (IOException ex) {
		GlobalVariable.internetOn = false;
		if (this.jCboxLoadSaveToken.getSelectedItem().toString().equals(GlobalVariable.userId)==false) 
		    JOptionPane.showMessageDialog(this, "Không thể truy cập mạng, bạn chỉ có thể đăng nhập với những tài khoản đã lưu!");
	    } finally {
		if (GlobalVariable.internetOn) {
		    try {
			LoginProcess.login();
			this.setVisible(false);
			index newIndexPage = new index();
			index.lb_name_mail.setText(GlobalVariable.userId);
			newIndexPage.setVisible(true);
		    } catch (WrongLoginInfoException ex) {
			JOptionPane.showMessageDialog(this, ex.getMessage());
		    }
		} else {
//		    JOptionPane.showMessageDialog(this, "Không thể truy cập mạng, bạn chỉ có thể đăng nhập với những tài khoản đã lưu!");
		    if (this.jCboxLoadSaveToken.getSelectedItem().toString().equals(GlobalVariable.userId)) {
			this.setVisible(false);
			index newIndexPage = new index();
			index.lb_name_mail.setText(GlobalVariable.userId);
			newIndexPage.setVisible(true);
		    }
		}
	    }
	}
    }//GEN-LAST:event_bt_startActionPerformed

    private void lb_errorComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lb_errorComponentHidden
	// TODO add your handling code here:
    }//GEN-LAST:event_lb_errorComponentHidden

    private void tf_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_emailMouseClicked
	// TODO add your handling code here:
	lb_error.setVisible(false);
    }//GEN-LAST:event_tf_emailMouseClicked

    private void jCboxLoadSaveTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboxLoadSaveTokenActionPerformed
	// TODO add your handling code here:
	this.tf_email.setText(this.jCboxLoadSaveToken.getSelectedItem().toString());
    }//GEN-LAST:event_jCboxLoadSaveTokenActionPerformed

    public int checkmail() {
	try {
	    String pattern = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
		    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
	    String email = tf_email.getText();
	    if (email.matches(pattern)) {
		return 0;
	    }
	} catch (Exception e) {
	    e.printStackTrace();
	}
	return 1;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new welcome().setVisible(true);
//
//            }
//        });
//    }
    public static void lookAndFeel() {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new welcome().setVisible(true);
//
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton bt_start;
    private javax.swing.JCheckBox cb_remember;
    private javax.swing.JComboBox<String> jCboxLoadSaveToken;
    private javax.swing.JLabel lb_error;
    private javax.swing.JLabel lb_mail;
    private javax.swing.JLabel lb_wc;
    private javax.swing.JTextField tf_email;
    // End of variables declaration//GEN-END:variables
}
